# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.migrated.updateDir", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 2);
user_pref("browser.migration.version", 24);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.rights.3.shown", true);
user_pref("browser.search.isUS", false);
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.slowStartup.averageTime", 964);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20141126041045");
user_pref("browser.startup.homepage_override.mstone", "34.0.5");
user_pref("browser.taskbar.lastgroupid", "E7CF176E110C211B");
user_pref("browser.uitour.treatment.srch-chg-action", "ViewPage");
user_pref("browser.uitour.treatment.srch-chg-treatment", "firstrun_otherDefault");
user_pref("browser.uitour.whitelist.add.260", "");
user_pref("browser.uitour.whitelist.add.340", "");
user_pref("browser.uitour.whitelist.add.341", "");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1438618527431");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.firstRunTime", "1438532127431");
user_pref("datareporting.sessions.current.activeTicks", 2);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 900);
user_pref("datareporting.sessions.current.main", 64);
user_pref("datareporting.sessions.current.sessionRestored", 1002);
user_pref("datareporting.sessions.current.startTime", "1438532127129");
user_pref("datareporting.sessions.current.totalTime", 7);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:34.0.5");
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.installCache", "[{\"name\":\"winreg-app-global\",\"addons\":{\"otis@digitalpersona.com\":{\"descriptor\":\"C:\\\\Program Files (x86)\\\\Hewlett-Packard\\\\HP ProtectTools Security Manager\\\\Bin\\\\FirefoxExt\",\"mtime\":1432375403067,\"rdfTime\":1342776254000}}},{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"C:\\\\Program Files (x86)\\\\Mozilla Firefox\\\\browser\\\\extensions\\\\{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1435594120253,\"rdfTime\":1417010916000}}},{\"name\":\"winreg-app-user\",\"addons\":{\"mozilla_cc@internetdownloadmanager.com\":{\"descriptor\":\"C:\\\\Users\\\\VUMVO\\\\AppData\\\\Roaming\\\\IDM\\\\idmmzcc5\",\"mtime\":1438524287499,\"rdfTime\":1438524287452}}}]");
user_pref("extensions.lastAppVersion", "34.0.5");
user_pref("extensions.lastPlatformVersion", "34.0.5");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("gecko.buildID", "20141126041045");
user_pref("gecko.mstone", "34.0.5");
user_pref("gfx.direct3d.last_used_feature_level_idx", 0);
user_pref("loop.soft_start_ticket_number", 4159549);
user_pref("loop.throttled", false);
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1438532127);
user_pref("toolkit.telemetry.previousBuildID", "20141126041045");
